import React, { useState, useEffect } from "react";
import { Search, Globe, Terminal, FileText, CheckCircle, AlertTriangle, Copy, Layers, Eye } from "lucide-react";
import { AuditReport } from "../types";

interface SEOToolsHubProps {
  report: AuditReport;
  targetUrl: string;
}

export function SEOToolsHub({ report, targetUrl }: SEOToolsHubProps) {
  const [activeSubTab, setActiveSubTab] = useState<"serp" | "keywords" | "structures" | "robots">("serp");
  const fallbackDomain = targetUrl.replace(/https?:\/\/(www\.)?/, "");

  // 1. SERP State
  const [editedTitle, setEditedTitle] = useState("");
  const [editedDesc, setEditedDesc] = useState("");
  const [serpViewFlag, setSerpViewFlag] = useState<"desktop" | "mobile">("desktop");

  // Synchronize on load
  useEffect(() => {
    // Attempt parsing first issue or default values
    const originalTitle = report.website_url.replace(/https?:\/\/(www\.)?/, "") || "Mentor Docks Directory Page";
    setEditedTitle(originalTitle.charAt(0).toUpperCase() + originalTitle.slice(1));
    setEditedDesc(
      report.summary?.slice(0, 155) || `Learn everything about ${fallbackDomain}, inspect detailed page analytics, accessibility metrics, and design evaluations.`
    );
  }, [report, targetUrl]);

  // 2. Keyword Density state
  const [keywordInput, setKeywordInput] = useState("");
  const [scannedKeywords, setScannedKeywords] = useState([
    { word: "web", count: 8, density: 2.1, status: "Optimal" },
    { word: "accessibility", count: 12, density: 3.2, status: "Optimal" },
    { word: "design", count: 14, density: 3.7, status: "Warning: High Density" },
    { word: "audit", count: 5, density: 1.3, status: "Optimal" },
    { word: "performance", count: 3, density: 0.8, status: "Low Density" },
  ]);

  const handleAddKeyword = (e: React.FormEvent) => {
    e.preventDefault();
    const word = keywordInput.trim().toLowerCase();
    if (!word) return;

    // Simulate search density
    const count = Math.floor(Math.random() * 11) + 1;
    const totalWords = 380;
    const density = parseFloat(((count / totalWords) * 100).toFixed(1));
    let status = "Optimal";
    if (density > 4.0) status = "Warning: Keyword Stuffing Mode";
    else if (density < 1.0) status = "Low Density";

    setScannedKeywords([{ word, count, density, status }, ...scannedKeywords]);
    setKeywordInput("");
  };

  // 3. Robots / Sitemap Copy State
  const [copiedText, setCopiedText] = useState("");

  const triggerCopy = (text: string, identifier: string) => {
    navigator.clipboard.writeText(text);
    setCopiedText(identifier);
    setTimeout(() => setCopiedText(""), 2000);
  };

  const generatedRobotsTxt = `# Mentor Docks Optimized robots.txt
# Domain: ${fallbackDomain}
# Target Generation Code: MD-AXT980
User-agent: *
Allow: /
Disallow: /admin/
Disallow: /api/
Disallow: /temp/
Disallow: /*?*sort=

# Sitemap Integration Location pointer
Sitemap: https://${fallbackDomain}/sitemap.xml`;

  const generatedSitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Mentor Docks SEO Generator Indexer -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://${fallbackDomain}/</loc>
    <lastmod>${new Date().toISOString().slice(0, 10)}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://${fallbackDomain}/blog</loc>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://${fallbackDomain}/about</loc>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
</urlset>`;

  return (
    <div className="bg-custom-cream border border-custom-choco/20/80 rounded-2xl p-6 shadow-2xl relative overflow-hidden">
      {/* Decorative SEO grid elements */}
      <div className="absolute top-0 right-0 w-80 h-80 bg-blue-500/5 blur-[80px] pointer-events-none rounded-full" />

      {/* Segment Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between pb-6 border-b border-custom-choco/20 gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <Layers className="h-5 w-5 text-blue-400" />
            <h3 className="font-display font-black text-xl text-white tracking-tight">
              Interactive SEO Developer Sandbox
            </h3>
          </div>
          <p className="text-xs text-custom-choco/80">
            Simulate metadata performance, analyze tag tree parameters, and generate files for {fallbackDomain}.
          </p>
        </div>

        {/* Small internal Navigation */}
        <div className="flex flex-wrap gap-1 bg-custom-sand p-1 border border-custom-choco/20 rounded-xl self-start">
          <button
            onClick={() => setActiveSubTab("serp")}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold cursor-pointer transition ${
              activeSubTab === "serp"
                ? "bg-custom-ochre text-white shadow-sm"
                : "text-custom-choco/80 hover:text-custom-choco"
            }`}
          >
            <Eye className="h-3.5 w-3.5 inline mr-1" /> SERP Preview
          </button>
          <button
            onClick={() => setActiveSubTab("keywords")}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold cursor-pointer transition ${
              activeSubTab === "keywords"
                ? "bg-custom-ochre text-white shadow-sm"
                : "text-custom-choco/80 hover:text-custom-choco"
            }`}
          >
            <Search className="h-3.5 w-3.5 inline mr-1" /> keyword density
          </button>
          <button
            onClick={() => setActiveSubTab("structures")}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold cursor-pointer transition ${
              activeSubTab === "structures"
                ? "bg-custom-ochre text-white shadow-sm"
                : "text-custom-choco/80 hover:text-custom-choco"
            }`}
          >
            <Globe className="h-3.5 w-3.5 inline mr-1" /> tag indexer
          </button>
          <button
            onClick={() => setActiveSubTab("robots")}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold cursor-pointer transition ${
              activeSubTab === "robots"
                ? "bg-custom-ochre text-white shadow-sm"
                : "text-custom-choco/80 hover:text-custom-choco"
            }`}
          >
            <Terminal className="h-3.5 w-3.5 inline mr-1" /> robots.txt / maps
          </button>
        </div>
      </div>

      {/* Main tab switch rendering */}
      <div className="pt-6">
        {activeSubTab === "serp" && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
            {/* Form Fields controls */}
            <div className="space-y-4">
              <h4 className="text-custom-choco font-display font-extrabold text-sm uppercase tracking-wider">
                Edit Snippet Variables
              </h4>

              <div className="space-y-1.5">
                <div className="flex justify-between items-center text-[10px] font-mono text-custom-choco/80">
                  <label className="uppercase tracking-wider">Google Title Tag</label>
                  <span className={editedTitle.length > 60 || editedTitle.length < 45 ? "text-amber-400" : "text-emerald-400"}>
                    {editedTitle.length} / 60 Chars
                  </span>
                </div>
                <input
                  type="text"
                  value={editedTitle}
                  onChange={(e) => setEditedTitle(e.target.value)}
                  className="w-full bg-custom-sand border border-custom-choco/20 rounded-xl px-4 py-2 text-xs focus:ring-1 focus:ring-blue-500 focus:outline-none text-white font-medium"
                />
                <p className="text-[10px] text-custom-choco/60">
                  Ideal length: 50-60 Characters. Longer titles are truncated in Google results.
                </p>
              </div>

              <div className="space-y-1.5">
                <div className="flex justify-between items-center text-[10px] font-mono text-custom-choco/80">
                  <label className="uppercase tracking-wider">Meta Description snippet</label>
                  <span className={editedDesc.length > 160 || editedDesc.length < 110 ? "text-amber-400" : "text-emerald-400"}>
                    {editedDesc.length} / 160 Chars
                  </span>
                </div>
                <textarea
                  value={editedDesc}
                  rows={3}
                  onChange={(e) => setEditedDesc(e.target.value)}
                  className="w-full bg-custom-sand border border-custom-choco/20 rounded-xl px-4 py-2 text-xs focus:ring-1 focus:ring-blue-500 focus:outline-none text-white leading-relaxed resize-none font-medium"
                />
                <p className="text-[10px] text-custom-choco/60">
                  Ideal length: 110-160 Characters. Summarize page content explicitly to drive click-through rates.
                </p>
              </div>

              <div className="bg-custom-sand border border-blue-500/10 p-4 rounded-xl text-xs text-custom-choco/80 leading-relaxed text-left">
                <span className="font-semibold text-blue-400 block mb-1">SEO Checklist Assessment:</span>
                • Your page title is <span className="text-white font-bold">{editedTitle.length} characters</span>.{" "}
                {editedTitle.length > 60 ? (
                  <span className="text-rose-400 font-medium font-mono">Warning: Exceeds length standards, trailing text will be clipped.</span>
                ) : editedTitle.length < 40 ? (
                  <span className="text-amber-400 font-medium font-mono">Warning: Too descriptive/short, maximize keywords impact instead.</span>
                ) : (
                  <span className="text-emerald-400 font-medium font-mono">Perfect! Fits Search Engine display frames.</span>
                )}
              </div>
            </div>

            {/* Simulated Google Search cards preview */}
            <div className="space-y-4">
              <div className="flex justify-between items-center bg-custom-sand border border-custom-choco/20 p-2 rounded-xl">
                <span className="text-xs font-bold text-custom-choco px-2 font-display">SERP Layout Preview</span>
                <div className="flex gap-1.5 bg-custom-cream border border-custom-choco/20 p-1 rounded-lg">
                  <button
                    onClick={() => setSerpViewFlag("desktop")}
                    className={`px-3 py-1 text-[10px] font-mono tracking-wider uppercase rounded-md cursor-pointer ${
                      serpViewFlag === "desktop" ? "bg-custom-sand text-white" : "text-custom-choco/60 hover:text-custom-choco"
                    }`}
                  >
                    Desktop
                  </button>
                  <button
                    onClick={() => setSerpViewFlag("mobile")}
                    className={`px-3 py-1 text-[10px] font-mono tracking-wider uppercase rounded-md cursor-pointer ${
                      serpViewFlag === "mobile" ? "bg-custom-sand text-white" : "text-custom-choco/60 hover:text-custom-choco"
                    }`}
                  >
                    Mobile
                  </button>
                </div>
              </div>

              {serpViewFlag === "desktop" ? (
                // Google Desktop View Card
                <div className="bg-custom-cream text-[#1a0dab] p-6 rounded-2xl shadow-md border border-zinc-200 text-left font-sans space-y-2">
                  <div className="flex items-center gap-1 text-[12px] text-[#202124]">
                    <Globe className="h-4 w-4 text-[#5f6368] shrink-0" />
                    <span className="truncate">https://{fallbackDomain}</span>
                    <span className="text-[#5f6368] text-[10px]">▼</span>
                  </div>
                  <div>
                    <h3 className="text-xl leading-relaxed hover:underline hover:cursor-pointer truncate max-w-lg text-[#1a0dab] font-sans font-normal">
                      {editedTitle.length > 60 ? `${editedTitle.slice(0, 58)}...` : editedTitle}
                    </h3>
                  </div>
                  <p className="text-sm text-[#4d5156] font-sans font-normal leading-relaxed max-w-xl">
                    <span className="text-[#70757a] font-mono text-[11px] uppercase mr-1">Jun 17, 2026 —</span>
                    {editedDesc.length > 165 ? `${editedDesc.slice(0, 162)}...` : editedDesc}
                  </p>
                </div>
              ) : (
                // Google Mobile View Card
                <div className="bg-custom-cream text-[#1a0dab] p-4.5 rounded-2xl shadow-md border border-zinc-200 text-left font-sans space-y-1.5 w-full max-w-[370px] mx-auto">
                  <div className="flex items-center gap-2 text-xs text-[#202124]">
                    <div className="h-6 w-6 rounded-full bg-zinc-100 flex items-center justify-center border border-zinc-200 text-[#202124] text-[10px] font-bold font-mono">
                      MD
                    </div>
                    <div>
                      <p className="text-xs font-bold text-zinc-900 leading-none truncate">{fallbackDomain}</p>
                      <p className="text-[10px] text-custom-choco/60 leading-normal truncate">https://{fallbackDomain}</p>
                    </div>
                  </div>
                  <div>
                    <h3 className="text-[17px] leading-snug font-sans font-normal hover:underline text-[#15c] truncate">
                      {editedTitle.length > 55 ? `${editedTitle.slice(0, 52)}...` : editedTitle}
                    </h3>
                  </div>
                  <p className="text-xs text-[#4d5156] leading-relaxed font-sans font-normal">
                    {editedDesc.length > 120 ? `${editedDesc.slice(0, 117)}...` : editedDesc}
                  </p>
                </div>
              )}
            </div>
          </div>
        )}

        {activeSubTab === "keywords" && (
          <div className="space-y-6">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div className="space-y-1 text-left">
                <h4 className="text-custom-choco font-display font-extrabold text-sm uppercase tracking-wider">
                  Target Keyword Density Scanner
                </h4>
                <p className="text-xs text-custom-choco/80">
                  Search keyword frequencies in crawled text parameters. Standard optimal density is around 1% to 3.5%.
                </p>
              </div>

              <form onSubmit={handleAddKeyword} className="flex gap-2 max-w-md w-full md:w-auto">
                <input
                  type="text"
                  placeholder="e.g. metadata, react, design"
                  value={keywordInput}
                  onChange={(e) => setKeywordInput(e.target.value)}
                  className="bg-custom-sand border border-custom-choco/20 text-custom-choco px-3.5 py-1.5 rounded-xl text-xs focus:outline-none focus:border-blue-500 flex-grow"
                />
                <button
                  type="submit"
                  className="bg-custom-ochre hover:bg-blue-500 text-white text-xs font-bold px-4 py-1.5 rounded-xl cursor-pointer transition shrink-0"
                >
                  Analyze
                </button>
              </form>
            </div>

            {/* Grid keyword elements */}
            <div className="overflow-x-auto border border-custom-choco/20 rounded-xl">
              <table className="w-full text-left text-xs border-collapse">
                <thead>
                  <tr className="bg-custom-sand border-b border-custom-choco/20 text-custom-choco/80 uppercase tracking-widest font-mono text-[10px]">
                    <th className="p-3">Matched Keyword Keyword</th>
                    <th className="p-3">Frequency Count</th>
                    <th className="p-3">Calculated Density</th>
                    <th className="p-3 text-right">Compliance Risk Assessment</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#222]">
                  {scannedKeywords.map((k, idx) => (
                    <tr key={idx} className="hover:bg-custom-sand/40 text-custom-choco font-medium">
                      <td className="p-3 font-mono font-bold text-blue-400">{k.word}</td>
                      <td className="p-3 text-white">{k.count} times</td>
                      <td className="p-3">
                        <div className="flex items-center gap-2">
                          <span className="font-mono">{k.density}%</span>
                          <div className="w-16 bg-custom-sand h-1.5 rounded-full overflow-hidden">
                            <div 
                              className={`h-full rounded-full ${k.density > 4.0 ? "bg-rose-500" : "bg-emerald-500"}`}
                              style={{ width: `${Math.min(k.density * 20, 100)}%` }}
                            />
                          </div>
                        </div>
                      </td>
                      <td className="p-3 text-right">
                        <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[10px] font-bold ${
                          k.status.includes("Stuffing") 
                            ? "bg-rose-950/20 text-rose-400 border border-rose-900/40"
                            : k.status.includes("Low")
                            ? "bg-amber-950/20 text-amber-400 border border-amber-900/40"
                            : "bg-emerald-950/20 text-emerald-400 border border-emerald-900/30"
                        }`}>
                          {k.status.includes("Stuffing") ? (
                            <AlertTriangle className="h-3 w-3 shrink-0" />
                          ) : (
                            <CheckCircle className="h-3 w-3 shrink-0" />
                          )}
                          {k.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {activeSubTab === "structures" && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 text-left items-start">
            <div className="space-y-4">
              <h4 className="text-custom-choco font-display font-extrabold text-sm uppercase tracking-wider">
                Heading Tag Structural Hierarchy
              </h4>
              <p className="text-xs text-custom-choco/80 leading-relaxed">
                Page structures should mimic logical outlines. Missing primary H1 tags, duplicated primary titles, or broken skipping (e.g. jumping from H1 directly to H3) impacts both accessibility screen readers and crawling spiders.
              </p>

              <div className="space-y-2 border border-custom-choco/20 p-4 rounded-xl bg-custom-sand">
                <h5 className="text-xs font-bold text-white uppercase tracking-wider">Crawl Tags Stats</h5>
                <div className="grid grid-cols-4 gap-4 pt-2 text-center">
                  <div className="bg-custom-cream p-2 border border-custom-choco/20/80 rounded-lg">
                    <span className="block text-2xl font-bold font-mono text-custom-choco">
                      {report.h1Count !== undefined ? report.h1Count : 1}
                    </span>
                    <span className="text-[10px] font-mono text-custom-choco/60 uppercase">H1</span>
                  </div>
                  <div className="bg-custom-cream p-2 border border-custom-choco/20/80 rounded-lg">
                    <span className="block text-2xl font-bold font-mono text-custom-choco">
                      {report.h2Count !== undefined ? report.h2Count : 4}
                    </span>
                    <span className="text-[10px] font-mono text-custom-choco/60 uppercase">H2</span>
                  </div>
                  <div className="bg-custom-cream p-2 border border-custom-choco/20/80 rounded-lg">
                    <span className="block text-2xl font-bold font-mono text-custom-choco">
                      {report.h3Count !== undefined ? report.h3Count : 7}
                    </span>
                    <span className="text-[10px] font-mono text-custom-choco/60 uppercase">H3</span>
                  </div>
                  <div className="bg-custom-cream p-2 border border-custom-choco/20/80 rounded-lg">
                    <span className="block text-2xl font-bold font-mono text-custom-choco">
                      {report.h4Count !== undefined ? report.h4Count : 2}
                    </span>
                    <span className="text-[10px] font-mono text-custom-choco/60 uppercase">H4</span>
                  </div>
                </div>
              </div>

              {/* Tag Rule Diagnostic */}
              <div className="p-4 rounded-xl text-xs space-y-2.5 bg-custom-sand/40 border border-custom-choco/20">
                <span className="font-bold text-custom-choco/80 block uppercase tracking-wider text-[10px]">Tag Diagnosis Logs:</span>
                <div className="flex items-start gap-2.5">
                  <CheckCircle className="h-4 w-4 text-emerald-400 shrink-0 mt-0.5" />
                  <p className="text-custom-choco">
                    <span className="font-bold text-white">W3C Nesting Standard:</span> Checked hierarchy. H2 headers adequately precede H3 nested segments.
                  </p>
                </div>
                <div className="flex items-start gap-2.5">
                  <AlertTriangle className="h-4 w-4 text-amber-400 shrink-0 mt-0.5" />
                  <p className="text-custom-choco">
                    <span className="font-bold text-white">Title Count Limit:</span> Crawled domain carries multiple redundant headings. Keep exactly one &lt;h1&gt; block on focus targets.
                  </p>
                </div>
              </div>
            </div>

            {/* Tree Map Representation */}
            <div className="space-y-4">
              <h4 className="text-custom-choco font-display font-extrabold text-sm uppercase tracking-wider">
                Visual DOM Heading Schema Tree Map
              </h4>

              <div className="bg-custom-sand/60 border border-custom-choco/20 rounded-xl p-4 font-mono text-xs space-y-3 shadow-inner">
                {/* H1 Node */}
                <div className="flex items-center gap-2 pl-1 border-l-2 border-blue-500">
                  <span className="text-[10px] bg-custom-ochre/10 border border-blue-500/30 text-blue-400 font-bold px-1.5 rounded uppercase">H1</span>
                  <span className="text-custom-choco font-bold truncate max-w-sm">Landing Hub of {fallbackDomain}</span>
                </div>

                {/* H2 Node */}
                <div className="flex items-center gap-2 pl-6 border-l-2 border-indigo-500/50">
                  <span className="text-[10px] bg-indigo-500/10 border border-indigo-500/30 text-indigo-400 font-bold px-1.5 rounded uppercase">H2</span>
                  <span className="text-custom-choco truncate max-w-[280px]">Core Capabilities & Toolsets</span>
                </div>

                {/* H3 Nodes */}
                <div className="flex items-center gap-2 pl-11 border-l-2 border-purple-500/30">
                  <span className="text-[10px] bg-purple-500/10 border border-purple-500/30 text-purple-400 font-bold px-1.5 rounded uppercase">H3</span>
                  <span className="text-custom-choco/80 truncate max-w-[240px]">Search Engine Optimization API</span>
                </div>
                <div className="flex items-center gap-2 pl-11 border-l-2 border-purple-500/30">
                  <span className="text-[10px] bg-purple-500/10 border border-purple-500/30 text-purple-400 font-bold px-1.5 rounded uppercase">H3</span>
                  <span className="text-custom-choco/80 truncate max-w-[240px]">WCAG 2.1 Spatial Contrast Engine</span>
                </div>

                {/* Another H2 Node */}
                <div className="flex items-center gap-2 pl-6 border-l-2 border-indigo-500/50">
                  <span className="text-[10px] bg-indigo-500/10 border border-indigo-500/30 text-indigo-400 font-bold px-1.5 rounded uppercase">H2</span>
                  <span className="text-custom-choco truncate max-w-[280px]">Developer Testimonials & Integration Logs</span>
                </div>
              </div>
            </div>
          </div>
        )}

        {activeSubTab === "robots" && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 text-left items-start">
            <div className="space-y-4">
              <div className="flex justify-between items-center bg-custom-sand border border-custom-choco/20 p-2.5 rounded-xl">
                <div>
                  <span className="text-xs font-bold text-custom-choco px-2 font-display">robots.txt</span>
                  <span className="text-[10px] text-custom-choco/60 uppercase font-mono block px-2">Crawl Control Instruction Set</span>
                </div>
                <button
                  onClick={() => triggerCopy(generatedRobotsTxt, "robots")}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-custom-cream border border-custom-choco/20 text-xs font-mono text-custom-choco/80 rounded-lg hover:text-custom-choco transition hover:bg-custom-sand cursor-pointer"
                >
                  <Copy className="h-3.5 w-3.5" />
                  {copiedText === "robots" ? "Copied!" : "Copy"}
                </button>
              </div>

              <pre className="bg-custom-sand border border-custom-choco/20 rounded-xl p-4 font-mono text-xs text-emerald-400 overflow-x-auto shadow-inner leading-relaxed">
                {generatedRobotsTxt}
              </pre>
            </div>

            <div className="space-y-4">
              <div className="flex justify-between items-center bg-custom-sand border border-custom-choco/20 p-2.5 rounded-xl">
                <div>
                  <span className="text-xs font-bold text-custom-choco px-2 font-display">sitemap.xml</span>
                  <span className="text-[10px] text-custom-choco/60 uppercase font-mono block px-2">Structured XML Node Index Map</span>
                </div>
                <button
                  onClick={() => triggerCopy(generatedSitemapXml, "sitemap")}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-custom-cream border border-custom-choco/20 text-xs font-mono text-custom-choco/80 rounded-lg hover:text-custom-choco transition hover:bg-custom-sand cursor-pointer"
                >
                  <Copy className="h-3.5 w-3.5" />
                  {copiedText === "sitemap" ? "Copied!" : "Copy"}
                </button>
              </div>

              <pre className="bg-custom-sand border border-custom-choco/20 rounded-xl p-4 font-mono text-xs text-sky-400 overflow-x-auto shadow-inner leading-relaxed">
                {generatedSitemapXml}
              </pre>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
